# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RetailCompanion' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
  # Pods for RetailCompanion

  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

end
